# Generated by Django 5.2.1 on 2025-05-28 03:10

import uuid
from django.db import migrations, models

def generate_unique_uuids(apps, schema_editor):
    Leave = apps.get_model('leave', 'Leave')
    for leave in Leave.objects.all():
        leave.verification_uuid = uuid.uuid4()
        leave.save()


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0008_leave_reject_reason'),
    ]

    operations = [
        # 1) 先添加一个可空、无唯一约束的 UUIDField
        migrations.AddField(
            model_name='leave',
            name='verification_uuid',
            field=models.UUIDField(null=True, editable=False),
        ),
        # 2) 为每条已有记录生成真正唯一的 UUID
        migrations.RunPython(
            generate_unique_uuids,
            reverse_code=migrations.RunPython.noop
        ),
        # 3) 再把字段改回非空、唯一，并恢复 default
        migrations.AlterField(
            model_name='leave',
            name='verification_uuid',
            field=models.UUIDField(
                default=uuid.uuid4,
                unique=True,
                editable=False
            ),
        ),
    ]
