# Generated by Django 3.2.25 on 2025-05-28 04:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0009_leave_verification_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='verification_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='防伪校验码', unique=True),
        ),
    ]
